// ============================================
// WorkFlow Pro - Mock Data
// ============================================

import type {
  User,
  Customer,
  Contact,
  Material,
  WorkOrder,
  Quote,
  DashboardStats,
  WorkOrderImage,
} from '@/types';

// ============================================
// Users
// ============================================

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'anders@workflowpro.se',
    firstName: 'Anders',
    lastName: 'Svensson',
    fullName: 'Anders Svensson',
    role: 'admin',
    phone: '070-123 45 67',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anders',
    isActive: true,
    createdAt: new Date('2023-01-15'),
    lastLogin: new Date(),
  },
  {
    id: 'user-2',
    email: 'lisa@workflowpro.se',
    firstName: 'Lisa',
    lastName: 'Johansson',
    fullName: 'Lisa Johansson',
    role: 'manager',
    phone: '070-987 65 43',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    isActive: true,
    createdAt: new Date('2023-02-01'),
    lastLogin: new Date(),
  },
  {
    id: 'user-3',
    email: 'johan@workflowpro.se',
    firstName: 'Johan',
    lastName: 'Nilsson',
    fullName: 'Johan Nilsson',
    role: 'technician',
    phone: '070-456 78 90',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=johan',
    isActive: true,
    createdAt: new Date('2023-03-10'),
    lastLogin: new Date(),
  },
  {
    id: 'user-4',
    email: 'maria@workflowpro.se',
    firstName: 'Maria',
    lastName: 'Andersson',
    fullName: 'Maria Andersson',
    role: 'technician',
    phone: '070-234 56 78',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
    isActive: true,
    createdAt: new Date('2023-04-05'),
    lastLogin: new Date(),
  },
];

// ============================================
// Customers
// ============================================

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    type: 'company',
    name: 'Svenssons Bygg AB',
    orgNumber: '556123-4567',
    address: {
      street: 'Storgatan 12',
      postalCode: '123 45',
      city: 'Stockholm',
      country: 'Sverige',
    },
    email: 'info@svenssonbygg.se',
    phone: '08-123 45 67',
    website: 'www.svenssonbygg.se',
    paymentTerms: 30,
    notes: 'Stamkund sedan 2020',
    fortnoxCustomerId: 'F12345',
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-2',
    type: 'company',
    name: 'Lindqvist Fastigheter AB',
    orgNumber: '556789-0123',
    address: {
      street: 'Industrigatan 45',
      postalCode: '543 21',
      city: 'Göteborg',
      country: 'Sverige',
    },
    email: 'kontakt@lindqvistfast.se',
    phone: '031-987 65 43',
    paymentTerms: 14,
    fortnoxCustomerId: 'F12346',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-3',
    type: 'private',
    name: 'Erik Persson',
    personNumber: '19850115-1234',
    address: {
      street: 'Villavägen 8',
      postalCode: '543 21',
      city: 'Göteborg',
      country: 'Sverige',
    },
    email: 'erik.persson@email.se',
    phone: '070-876 54 32',
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-4',
    type: 'company',
    name: 'Nordic Property Management AB',
    orgNumber: '559876-5432',
    address: {
      street: 'Kungsgatan 88',
      postalCode: '111 22',
      city: 'Stockholm',
      country: 'Sverige',
    },
    email: 'info@nordicpm.se',
    phone: '08-555 12 34',
    website: 'www.nordicpm.se',
    paymentTerms: 30,
    fortnoxCustomerId: 'F12347',
    createdAt: new Date('2023-04-10'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-5',
    type: 'private',
    name: 'Anna Karlsson',
    personNumber: '19900320-5678',
    address: {
      street: 'Björkvägen 15',
      postalCode: '234 56',
      city: 'Malmö',
      country: 'Sverige',
    },
    email: 'anna.karlsson@email.se',
    phone: '070-345 67 89',
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date(),
  },
  {
    id: 'cust-6',
    type: 'company',
    name: 'Tech Solutions Sverige AB',
    orgNumber: '559012-3456',
    address: {
      street: 'Datavägen 10',
      postalCode: '436 32',
      city: 'Askim',
      country: 'Sverige',
    },
    email: 'support@techsolutions.se',
    phone: '031-123 45 67',
    website: 'www.techsolutions.se',
    paymentTerms: 30,
    fortnoxCustomerId: 'F12348',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date(),
  },
];

// ============================================
// Contacts
// ============================================

export const mockContacts: Contact[] = [
  {
    id: 'contact-1',
    customerId: 'cust-1',
    firstName: 'Anders',
    lastName: 'Svensson',
    fullName: 'Anders Svensson',
    email: 'anders@svenssonbygg.se',
    phone: '070-123 45 67',
    mobile: '070-123 45 67',
    title: 'VD',
    isPrimary: true,
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'contact-2',
    customerId: 'cust-1',
    firstName: 'Maria',
    lastName: 'Svensson',
    fullName: 'Maria Svensson',
    email: 'maria@svenssonbygg.se',
    phone: '070-234 56 78',
    title: 'Ekonomi',
    isPrimary: false,
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date(),
  },
  {
    id: 'contact-3',
    customerId: 'cust-2',
    firstName: 'Peter',
    lastName: 'Lindqvist',
    fullName: 'Peter Lindqvist',
    email: 'peter@lindqvistfast.se',
    phone: '070-345 67 89',
    mobile: '070-345 67 89',
    title: 'Fastighetschef',
    isPrimary: true,
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date(),
  },
  {
    id: 'contact-4',
    customerId: 'cust-4',
    firstName: 'Sara',
    lastName: 'Nordström',
    fullName: 'Sara Nordström',
    email: 'sara@nordicpm.se',
    phone: '070-456 78 90',
    mobile: '070-456 78 90',
    title: 'Driftansvarig',
    isPrimary: true,
    createdAt: new Date('2023-04-10'),
    updatedAt: new Date(),
  },
  {
    id: 'contact-5',
    customerId: 'cust-6',
    firstName: 'Marcus',
    lastName: 'Dahlberg',
    fullName: 'Marcus Dahlberg',
    email: 'marcus@techsolutions.se',
    phone: '070-567 89 01',
    mobile: '070-567 89 01',
    title: 'IT-ansvarig',
    isPrimary: true,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date(),
  },
];

// ============================================
// Materials
// ============================================

export const mockMaterials: Material[] = [
  {
    id: 'mat-1',
    articleNumber: 'E001',
    name: 'Kabel 3x1.5 mm²',
    description: 'Installationskabel för inomhusbruk',
    unit: 'm',
    price: 25,
    purchasePrice: 15,
    supplier: 'ahlsell',
    supplierArticleNumber: 'AH-4521',
    category: 'El',
    subcategory: 'Kabel',
    stockQuantity: 150,
    minStockLevel: 50,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-2',
    articleNumber: 'E002',
    name: 'Vägguttag 1-vägs',
    description: 'Jordat vägguttag vit',
    unit: 'st',
    price: 89,
    purchasePrice: 45,
    supplier: 'ahlsell',
    supplierArticleNumber: 'AH-4522',
    category: 'El',
    subcategory: 'Utan',
    stockQuantity: 45,
    minStockLevel: 20,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-3',
    articleNumber: 'E003',
    name: 'Kopplingsdosa',
    description: 'Dold kopplingsdosa 50x50mm',
    unit: 'st',
    price: 45,
    purchasePrice: 22,
    supplier: 'ahlsell',
    supplierArticleNumber: 'AH-4523',
    category: 'El',
    subcategory: 'Koppling',
    stockQuantity: 80,
    minStockLevel: 30,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-4',
    articleNumber: 'E004',
    name: 'Säkring 10A',
    description: 'Automatsäkring 10A C-karaktär',
    unit: 'st',
    price: 125,
    purchasePrice: 65,
    supplier: 'copiax',
    supplierArticleNumber: 'CX-1234',
    category: 'El',
    subcategory: 'Säkring',
    stockQuantity: 25,
    minStockLevel: 15,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-5',
    articleNumber: 'E005',
    name: 'Elcentral 12-moduler',
    description: 'Infälld elcentral med 12 moduler',
    unit: 'st',
    price: 895,
    purchasePrice: 450,
    supplier: 'ahlsell',
    supplierArticleNumber: 'AH-4524',
    category: 'El',
    subcategory: 'Central',
    stockQuantity: 8,
    minStockLevel: 5,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-6',
    articleNumber: 'R001',
    name: 'Rör 16mm',
    description: 'PVC-rör för elkabel 16mm',
    unit: 'm',
    price: 18,
    purchasePrice: 9,
    supplier: 'custom',
    category: 'Rör',
    subcategory: 'PVC',
    stockQuantity: 200,
    minStockLevel: 100,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-7',
    articleNumber: 'B001',
    name: 'Skruv M6x40',
    description: 'Universalskruv M6x40mm',
    unit: 'st',
    price: 3,
    purchasePrice: 1,
    supplier: 'custom',
    category: 'Befestning',
    stockQuantity: 500,
    minStockLevel: 200,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
  {
    id: 'mat-8',
    articleNumber: 'E006',
    name: 'LED-armatur 600mm',
    description: 'LED-list 600mm 18W 4000K',
    unit: 'st',
    price: 349,
    purchasePrice: 175,
    supplier: 'ahlsell',
    supplierArticleNumber: 'AH-4525',
    category: 'Belysning',
    subcategory: 'LED',
    stockQuantity: 15,
    minStockLevel: 10,
    isActive: true,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date(),
  },
];

// ============================================
// Work Order Images
// ============================================

export const mockWorkOrderImages: WorkOrderImage[] = [
  {
    id: 'img-1',
    workOrderId: 'wo-1',
    url: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=200',
    caption: 'Före installation',
    uploadedBy: 'user-3',
    uploadedAt: new Date('2024-01-12'),
    fileSize: 2048000,
    mimeType: 'image/jpeg',
  },
  {
    id: 'img-2',
    workOrderId: 'wo-1',
    url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200',
    caption: 'Under arbetet',
    uploadedBy: 'user-3',
    uploadedAt: new Date('2024-01-13'),
    fileSize: 1843200,
    mimeType: 'image/jpeg',
  },
  {
    id: 'img-3',
    workOrderId: 'wo-3',
    url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=200',
    caption: 'Elcentral före',
    uploadedBy: 'user-4',
    uploadedAt: new Date('2024-01-14'),
    fileSize: 2560000,
    mimeType: 'image/jpeg',
  },
];

// ============================================
// Work Orders
// ============================================

export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'wo-1',
    orderNumber: 'WO-2024-001',
    title: 'El-installation kök',
    description: 'Installation av nya eluttag och belysning i kök. Kunden önskar 4 nya uttag och 2 LED-spotlights under skåpen.',
    status: 'completed',
    priority: 'medium',
    customerId: 'cust-3',
    customer: mockCustomers[2],
    contactId: undefined,
    assignedTo: 'user-3',
    assignedUser: mockUsers[2],
    createdBy: 'user-1',
    createdByUser: mockUsers[0],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
    scheduledDate: new Date('2024-01-15'),
    startedAt: new Date('2024-01-15T08:00:00'),
    completedAt: new Date('2024-01-15T16:00:00'),
    estimatedHours: 6,
    actualHours: 8,
    materials: [
      {
        id: 'wom-1',
        workOrderId: 'wo-1',
        materialId: 'mat-1',
        material: mockMaterials[0],
        quantity: 15,
        unitPrice: 25,
        totalPrice: 375,
        notes: 'Kabeldragning',
      },
      {
        id: 'wom-2',
        workOrderId: 'wo-1',
        materialId: 'mat-2',
        material: mockMaterials[1],
        quantity: 4,
        unitPrice: 89,
        totalPrice: 356,
        notes: 'Nya uttag',
      },
      {
        id: 'wom-3',
        workOrderId: 'wo-1',
        materialId: 'mat-3',
        material: mockMaterials[2],
        quantity: 4,
        unitPrice: 45,
        totalPrice: 180,
        notes: 'Kopplingsdosor',
      },
    ],
    travels: [
      {
        id: 'trav-1',
        workOrderId: 'wo-1',
        userId: 'user-3',
        user: mockUsers[2],
        date: new Date('2024-01-15'),
        distanceKm: 45,
        travelTimeMinutes: 60,
        cost: 450,
        notes: 'Tur och retur',
        createdAt: new Date('2024-01-15'),
      },
    ],
    timeEntries: [
      {
        id: 'te-1',
        workOrderId: 'wo-1',
        userId: 'user-3',
        user: mockUsers[2],
        date: new Date('2024-01-15'),
        startTime: new Date('2024-01-15T08:00:00'),
        endTime: new Date('2024-01-15T16:00:00'),
        breakMinutes: 60,
        totalMinutes: 420,
        notes: 'Installation klar',
        isBillable: true,
        hourlyRate: 650,
        totalCost: 4550,
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
      },
    ],
    images: [mockWorkOrderImages[0], mockWorkOrderImages[1]],
    documents: [],
    materialCost: 911,
    laborCost: 4550,
    travelCost: 450,
    totalAmount: 5911,
    quoteId: 'qt-1',
    fortnoxInvoiceId: undefined,
    isInvoiced: false,
    notes: 'Kunden nöjd med resultatet',
    internalNotes: 'Nästa gång: kontrollera jordfelsbrytare',
  },
  {
    id: 'wo-2',
    orderNumber: 'WO-2024-002',
    title: 'Ny el-central',
    description: 'Byte av gammal el-central till ny modern central med jordfelsbrytare.',
    status: 'started',
    priority: 'high',
    customerId: 'cust-1',
    customer: mockCustomers[0],
    contactId: 'contact-1',
    contact: mockContacts[0],
    assignedTo: 'user-4',
    assignedUser: mockUsers[3],
    createdBy: 'user-2',
    createdByUser: mockUsers[1],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-16'),
    scheduledDate: new Date('2024-01-16'),
    startedAt: new Date('2024-01-16T09:00:00'),
    completedAt: undefined,
    estimatedHours: 10,
    actualHours: 4,
    materials: [
      {
        id: 'wom-4',
        workOrderId: 'wo-2',
        materialId: 'mat-5',
        material: mockMaterials[4],
        quantity: 1,
        unitPrice: 895,
        totalPrice: 895,
        notes: 'Ny elcentral',
      },
      {
        id: 'wom-5',
        workOrderId: 'wo-2',
        materialId: 'mat-4',
        material: mockMaterials[3],
        quantity: 8,
        unitPrice: 125,
        totalPrice: 1000,
        notes: 'Säkringar',
      },
    ],
    travels: [],
    timeEntries: [
      {
        id: 'te-2',
        workOrderId: 'wo-2',
        userId: 'user-4',
        user: mockUsers[3],
        date: new Date('2024-01-16'),
        startTime: new Date('2024-01-16T09:00:00'),
        endTime: new Date('2024-01-16T13:00:00'),
        breakMinutes: 0,
        totalMinutes: 240,
        notes: 'Påbörjat arbetet',
        isBillable: true,
        hourlyRate: 650,
        totalCost: 2600,
        createdAt: new Date('2024-01-16'),
        updatedAt: new Date('2024-01-16'),
      },
    ],
    images: [mockWorkOrderImages[2]],
    documents: [],
    materialCost: 1895,
    laborCost: 2600,
    travelCost: 0,
    totalAmount: 4495,
    quoteId: 'qt-2',
    fortnoxInvoiceId: undefined,
    isInvoiced: false,
    notes: '',
    internalNotes: 'Fortsätter imorgon',
  },
  {
    id: 'wo-3',
    orderNumber: 'WO-2024-003',
    title: 'Belysningsbyte kontor',
    description: 'Byte av gamla lysrör till nya LED-armaturer i kontorslandskap. Totalt 20 armaturer.',
    status: 'available',
    priority: 'medium',
    customerId: 'cust-4',
    customer: mockCustomers[3],
    contactId: 'contact-4',
    contact: mockContacts[3],
    assignedTo: undefined,
    assignedUser: undefined,
    createdBy: 'user-1',
    createdByUser: mockUsers[0],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    scheduledDate: new Date('2024-01-20'),
    startedAt: undefined,
    completedAt: undefined,
    estimatedHours: 12,
    actualHours: 0,
    materials: [],
    travels: [],
    timeEntries: [],
    images: [],
    documents: [],
    materialCost: 0,
    laborCost: 0,
    travelCost: 0,
    totalAmount: 0,
    quoteId: undefined,
    fortnoxInvoiceId: undefined,
    isInvoiced: false,
    notes: 'Tillgänglig för tilldelning',
    internalNotes: '',
  },
  {
    id: 'wo-4',
    orderNumber: 'WO-2024-004',
    title: 'Felanmälan belysning',
    description: 'Flera lampor i garaget har slutat fungera. Behöver felsökning och åtgärd.',
    status: 'taken',
    priority: 'urgent',
    customerId: 'cust-2',
    customer: mockCustomers[1],
    contactId: 'contact-3',
    contact: mockContacts[2],
    assignedTo: 'user-3',
    assignedUser: mockUsers[2],
    createdBy: 'user-2',
    createdByUser: mockUsers[1],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    scheduledDate: new Date('2024-01-17'),
    startedAt: undefined,
    completedAt: undefined,
    estimatedHours: 3,
    actualHours: 0,
    materials: [],
    travels: [],
    timeEntries: [],
    images: [],
    documents: [],
    materialCost: 0,
    laborCost: 0,
    travelCost: 0,
    totalAmount: 0,
    quoteId: undefined,
    fortnoxInvoiceId: undefined,
    isInvoiced: false,
    notes: 'Akut ärende',
    internalNotes: '',
  },
  {
    id: 'wo-5',
    orderNumber: 'WO-2024-005',
    title: 'Installation laddbox',
    description: 'Installation av laddbox för elbil hemma hos privatperson.',
    status: 'paused',
    priority: 'medium',
    customerId: 'cust-5',
    customer: mockCustomers[4],
    contactId: undefined,
    assignedTo: 'user-4',
    assignedUser: mockUsers[3],
    createdBy: 'user-1',
    createdByUser: mockUsers[0],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-14'),
    scheduledDate: new Date('2024-01-13'),
    startedAt: new Date('2024-01-13T10:00:00'),
    completedAt: undefined,
    estimatedHours: 6,
    actualHours: 2,
    materials: [],
    travels: [],
    timeEntries: [
      {
        id: 'te-3',
        workOrderId: 'wo-5',
        userId: 'user-4',
        user: mockUsers[3],
        date: new Date('2024-01-13'),
        startTime: new Date('2024-01-13T10:00:00'),
        endTime: new Date('2024-01-13T12:00:00'),
        breakMinutes: 0,
        totalMinutes: 120,
        notes: 'Pausad - väntar på delar',
        isBillable: true,
        hourlyRate: 650,
        totalCost: 1300,
        createdAt: new Date('2024-01-13'),
        updatedAt: new Date('2024-01-13'),
      },
    ],
    images: [],
    documents: [],
    materialCost: 0,
    laborCost: 1300,
    travelCost: 0,
    totalAmount: 1300,
    quoteId: undefined,
    fortnoxInvoiceId: undefined,
    isInvoiced: false,
    notes: 'Pausad - väntar på laddbox från leverantör',
    internalNotes: 'Beställt laddbox, beräknad leverans 20/1',
  },
  {
    id: 'wo-6',
    orderNumber: 'WO-2024-006',
    title: 'Serviceavtal IT-rum',
    description: 'Månatlig service av elsystem i serverrum. Kontroll av UPS och säkringar.',
    status: 'invoiced',
    priority: 'low',
    customerId: 'cust-6',
    customer: mockCustomers[5],
    contactId: 'contact-5',
    contact: mockContacts[4],
    assignedTo: 'user-3',
    assignedUser: mockUsers[2],
    createdBy: 'user-2',
    createdByUser: mockUsers[1],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-08'),
    scheduledDate: new Date('2024-01-08'),
    startedAt: new Date('2024-01-08T09:00:00'),
    completedAt: new Date('2024-01-08T11:00:00'),
    estimatedHours: 2,
    actualHours: 2,
    materials: [],
    travels: [
      {
        id: 'trav-2',
        workOrderId: 'wo-6',
        userId: 'user-3',
        user: mockUsers[2],
        date: new Date('2024-01-08'),
        distanceKm: 25,
        travelTimeMinutes: 35,
        cost: 250,
        notes: '',
        createdAt: new Date('2024-01-08'),
      },
    ],
    timeEntries: [
      {
        id: 'te-4',
        workOrderId: 'wo-6',
        userId: 'user-3',
        user: mockUsers[2],
        date: new Date('2024-01-08'),
        startTime: new Date('2024-01-08T09:00:00'),
        endTime: new Date('2024-01-08T11:00:00'),
        breakMinutes: 0,
        totalMinutes: 120,
        notes: 'Service utförd',
        isBillable: true,
        hourlyRate: 650,
        totalCost: 1300,
        createdAt: new Date('2024-01-08'),
        updatedAt: new Date('2024-01-08'),
      },
    ],
    images: [],
    documents: [],
    materialCost: 0,
    laborCost: 1300,
    travelCost: 250,
    totalAmount: 1550,
    quoteId: undefined,
    fortnoxInvoiceId: 'F-2024-001',
    isInvoiced: true,
    invoiceDate: new Date('2024-01-09'),
    notes: '',
    internalNotes: '',
  },
];

// ============================================
// Quotes
// ============================================

export const mockQuotes: Quote[] = [
  {
    id: 'qt-1',
    quoteNumber: 'QT-2024-001',
    title: 'El-installation kök',
    description: 'Installation av nya eluttag och belysning i kök.',
    status: 'accepted',
    customerId: 'cust-3',
    customer: mockCustomers[2],
    contactId: undefined,
    createdBy: 'user-1',
    createdByUser: mockUsers[0],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-08'),
    validUntil: new Date('2024-02-05'),
    sentAt: new Date('2024-01-06'),
    acceptedAt: new Date('2024-01-08'),
    rejectedAt: undefined,
    rejectionReason: undefined,
    items: [
      {
        id: 'qi-1',
        quoteId: 'qt-1',
        description: 'Material inklusive kabel, uttag och kopplingsdosor',
        quantity: 1,
        unit: 'st',
        unitPrice: 911,
        discountPercent: 0,
        totalPrice: 911,
      },
      {
        id: 'qi-2',
        quoteId: 'qt-1',
        description: 'Arbete inklusive resa',
        quantity: 8,
        unit: 'tim',
        unitPrice: 650,
        discountPercent: 0,
        totalPrice: 5200,
      },
    ],
    subtotal: 6111,
    discountPercent: 0,
    discountAmount: 0,
    vatPercent: 25,
    vatAmount: 1527.75,
    totalAmount: 7638.75,
    workOrderId: 'wo-1',
    notes: '',
    internalNotes: '',
  },
  {
    id: 'qt-2',
    quoteNumber: 'QT-2024-002',
    title: 'Ny el-central',
    description: 'Byte av gammal el-central till ny modern central.',
    status: 'accepted',
    customerId: 'cust-1',
    customer: mockCustomers[0],
    contactId: 'contact-1',
    contact: mockContacts[0],
    createdBy: 'user-2',
    createdByUser: mockUsers[1],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-10'),
    validUntil: new Date('2024-02-08'),
    sentAt: new Date('2024-01-09'),
    acceptedAt: new Date('2024-01-10'),
    items: [
      {
        id: 'qi-3',
        quoteId: 'qt-2',
        description: 'Elcentral 12-moduler',
        quantity: 1,
        unit: 'st',
        unitPrice: 895,
        discountPercent: 0,
        totalPrice: 895,
      },
      {
        id: 'qi-4',
        quoteId: 'qt-2',
        description: 'Säkringar',
        quantity: 8,
        unit: 'st',
        unitPrice: 125,
        discountPercent: 0,
        totalPrice: 1000,
      },
      {
        id: 'qi-5',
        quoteId: 'qt-2',
        description: 'Arbete',
        quantity: 10,
        unit: 'tim',
        unitPrice: 650,
        discountPercent: 0,
        totalPrice: 6500,
      },
    ],
    subtotal: 8395,
    discountPercent: 0,
    discountAmount: 0,
    vatPercent: 25,
    vatAmount: 2098.75,
    totalAmount: 10493.75,
    workOrderId: 'wo-2',
    notes: '',
    internalNotes: '',
  },
  {
    id: 'qt-3',
    quoteNumber: 'QT-2024-003',
    title: 'Belysningsbyte kontor',
    description: 'Byte av gamla lysrör till nya LED-armaturer.',
    status: 'sent',
    customerId: 'cust-4',
    customer: mockCustomers[3],
    contactId: 'contact-4',
    contact: mockContacts[3],
    createdBy: 'user-1',
    createdByUser: mockUsers[0],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-13'),
    validUntil: new Date('2024-02-12'),
    sentAt: new Date('2024-01-13'),
    acceptedAt: undefined,
    items: [
      {
        id: 'qi-6',
        quoteId: 'qt-3',
        description: 'LED-armatur 600mm',
        quantity: 20,
        unit: 'st',
        unitPrice: 349,
        discountPercent: 10,
        totalPrice: 6282,
      },
      {
        id: 'qi-7',
        quoteId: 'qt-3',
        description: 'Arbete inklusive montering',
        quantity: 12,
        unit: 'tim',
        unitPrice: 650,
        discountPercent: 0,
        totalPrice: 7800,
      },
    ],
    subtotal: 14082,
    discountPercent: 0,
    discountAmount: 0,
    vatPercent: 25,
    vatAmount: 3520.5,
    totalAmount: 17602.5,
    workOrderId: undefined,
    notes: '',
    internalNotes: 'Väntar på svar',
  },
  {
    id: 'qt-4',
    quoteNumber: 'QT-2024-004',
    title: 'Installation laddbox',
    description: 'Installation av laddbox för elbil.',
    status: 'draft',
    customerId: 'cust-5',
    customer: mockCustomers[4],
    contactId: undefined,
    createdBy: 'user-1',
    createdByUser: mockUsers[0],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    validUntil: new Date('2024-02-15'),
    sentAt: undefined,
    acceptedAt: undefined,
    items: [
      {
        id: 'qi-8',
        quoteId: 'qt-4',
        description: 'Laddbox 11kW',
        quantity: 1,
        unit: 'st',
        unitPrice: 4500,
        discountPercent: 0,
        totalPrice: 4500,
      },
      {
        id: 'qi-9',
        quoteId: 'qt-4',
        description: 'Installation',
        quantity: 6,
        unit: 'tim',
        unitPrice: 650,
        discountPercent: 0,
        totalPrice: 3900,
      },
    ],
    subtotal: 8400,
    discountPercent: 0,
    discountAmount: 0,
    vatPercent: 25,
    vatAmount: 2100,
    totalAmount: 10500,
    workOrderId: undefined,
    notes: 'Utkast - ej skickad',
    internalNotes: '',
  },
  {
    id: 'qt-5',
    quoteNumber: 'QT-2024-005',
    title: 'Renovering badrum',
    description: 'Komplett el-renovering av badrum inklusive golvvärme.',
    status: 'rejected',
    customerId: 'cust-3',
    customer: mockCustomers[2],
    contactId: undefined,
    createdBy: 'user-2',
    createdByUser: mockUsers[1],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-10'),
    validUntil: new Date('2024-02-05'),
    sentAt: new Date('2024-01-06'),
    acceptedAt: undefined,
    rejectedAt: new Date('2024-01-10'),
    rejectionReason: 'För högt pris',
    items: [
      {
        id: 'qi-10',
        quoteId: 'qt-5',
        description: 'Material',
        quantity: 1,
        unit: 'st',
        unitPrice: 8500,
        discountPercent: 0,
        totalPrice: 8500,
      },
      {
        id: 'qi-11',
        quoteId: 'qt-5',
        description: 'Arbete',
        quantity: 20,
        unit: 'tim',
        unitPrice: 650,
        discountPercent: 0,
        totalPrice: 13000,
      },
    ],
    subtotal: 21500,
    discountPercent: 0,
    discountAmount: 0,
    vatPercent: 25,
    vatAmount: 5375,
    totalAmount: 26875,
    workOrderId: undefined,
    notes: '',
    internalNotes: 'Kunden tyckte priset var för högt',
  },
];

// ============================================
// Dashboard Stats
// ============================================

export const mockDashboardStats: DashboardStats = {
  workOrders: {
    available: 1,
    taken: 1,
    started: 1,
    paused: 1,
    completed: 1,
    invoiced: 1,
    total: 6,
  },
  quotes: {
    draft: 1,
    sent: 1,
    accepted: 2,
    rejected: 1,
    total: 5,
  },
  revenue: {
    thisMonth: 1550,
    lastMonth: 0,
    thisYear: 1550,
    pending: 11706,
  },
  recentWorkOrders: mockWorkOrders.slice(0, 5),
  recentQuotes: mockQuotes.slice(0, 3),
  upcomingWorkOrders: mockWorkOrders.filter(wo => 
    wo.status === 'available' || wo.status === 'taken' || wo.status === 'started'
  ),
};

// ============================================
// Helper Functions
// ============================================

export const getStatusLabel = (status: string): string => {
  const labels: Record<string, string> = {
    // Work order statuses
    available: 'Ledig',
    taken: 'Tagen',
    started: 'Påbörjad',
    paused: 'Pausad',
    completed: 'Avslutad',
    invoiced: 'Fakturerad',
    // Quote statuses
    draft: 'Utkast',
    sent: 'Skickad',
    accepted: 'Accepterad',
    rejected: 'Avslagen',
    revised: 'Omgjord',
  };
  return labels[status] || status;
};

export const getStatusColor = (status: string): string => {
  const colors: Record<string, string> = {
    // Work order statuses
    available: 'bg-green-500',
    taken: 'bg-amber-500',
    started: 'bg-blue-500',
    paused: 'bg-orange-500',
    completed: 'bg-emerald-500',
    invoiced: 'bg-violet-500',
    // Quote statuses
    draft: 'bg-slate-400',
    sent: 'bg-amber-500',
    accepted: 'bg-green-500',
    rejected: 'bg-red-500',
    revised: 'bg-orange-500',
  };
  return colors[status] || 'bg-gray-400';
};

export const getPriorityLabel = (priority: string): string => {
  const labels: Record<string, string> = {
    low: 'Låg',
    medium: 'Medium',
    high: 'Hög',
    urgent: 'Akut',
  };
  return labels[priority] || priority;
};

export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('sv-SE', {
    style: 'currency',
    currency: 'SEK',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const formatDate = (date: Date | undefined): string => {
  if (!date) return '-';
  return new Intl.DateTimeFormat('sv-SE', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  }).format(date);
};

export const formatDateTime = (date: Date | undefined): string => {
  if (!date) return '-';
  return new Intl.DateTimeFormat('sv-SE', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
};
